//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsLab_NikitaAmol {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalUIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalUIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsLab_NikitaAmol.GlobalUIStrings", typeof(GlobalUIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Settings....
        /// </summary>
        internal static string addDialogBoxName {
            get {
                return ResourceManager.GetString("addDialogBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        internal static string addDialogFontSizeLabel {
            get {
                return ResourceManager.GetString("addDialogFontSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Alignment.
        /// </summary>
        internal static string addDialogGBoxName {
            get {
                return ResourceManager.GetString("addDialogGBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Text.
        /// </summary>
        internal static string addTextButtonName {
            get {
                return ResourceManager.GetString("addTextButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional text.
        /// </summary>
        internal static string addTextName {
            get {
                return ResourceManager.GetString("addTextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string authorName {
            get {
                return ResourceManager.GetString("authorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string backgroundName {
            get {
                return ResourceManager.GetString("backgroundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancelButton {
            get {
                return ResourceManager.GetString("cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string changeButtonName {
            get {
                return ResourceManager.GetString("changeButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Settings.
        /// </summary>
        internal static string colorSetName {
            get {
                return ResourceManager.GetString("colorSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string cRadio {
            get {
                return ResourceManager.GetString("cRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string englishName {
            get {
                return ResourceManager.GetString("englishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string fileMenuName {
            get {
                return ResourceManager.GetString("fileMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string fileNewName {
            get {
                return ResourceManager.GetString("fileNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string fileOpenName {
            get {
                return ResourceManager.GetString("fileOpenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string fileSaveName {
            get {
                return ResourceManager.GetString("fileSaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Cover Designer.
        /// </summary>
        internal static string formName {
            get {
                return ResourceManager.GetString("formName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string lRadio {
            get {
                return ResourceManager.GetString("lRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string newBigHeight {
            get {
                return ResourceManager.GetString("newBigHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string newBigWidth {
            get {
                return ResourceManager.GetString("newBigWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Cover....
        /// </summary>
        internal static string newCoverDialogName {
            get {
                return ResourceManager.GetString("newCoverDialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spine Width.
        /// </summary>
        internal static string newSmallWidth {
            get {
                return ResourceManager.GetString("newSmallWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        internal static string nothing {
            get {
                return ResourceManager.GetString("nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string rRadio {
            get {
                return ResourceManager.GetString("rRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string rusName {
            get {
                return ResourceManager.GetString("rusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string setLangName {
            get {
                return ResourceManager.GetString("setLangName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settingsMenuName {
            get {
                return ResourceManager.GetString("settingsMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string textName {
            get {
                return ResourceManager.GetString("textName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string titleName {
            get {
                return ResourceManager.GetString("titleName", resourceCulture);
            }
        }
    }
}
